{
 "title": "Flow-monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "EPS Savings",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(increase(logiq_namespace_app_message_count[15m]))-sum(increase(logiq_logflow_forwards_flush_count[15m])))/sum(increase(logiq_namespace_app_message_count[15m]))*100"
    }
   ]
  },
  {
   "title": "Data pipeline distribution",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (app, exported_namespace, target) (increase(logiq_logflow_forwards_count[$interval]))"
    }
   ]
  },
  {
   "title": "Egress- messages/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "round(sum by (target) (rate(logiq_logflow_forwards_flush_count[5m])),0.01)"
    }
   ]
  }
 ]
}