{
 "title": "Logflow",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "Messages/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(logiq_message_count[5m])),1)"
    }
   ]
  },
  {
   "title": "Forwarders",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "select name as Name, schema as Forwarder, config  from forwards"
    }
   ]
  },
  {
   "title": "Log Flow distribution (24h)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum by (target) (increase(logiq_logflow_forwards_count[24h])),1)"
    }
   ]
  },
  {
   "title": "Ingest GB/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "round(sum by (connectionType) (rate(logiq_data_received_bytes[5m]))*3600/1000000000,0.001)"
    }
   ]
  }
 ]
}