{
 "title": "Logs overview",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Messages/sec",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(rate(logiq_message_count[5m])),1)"
    }
   ]
  },
  {
   "title": "Ingest capacity utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(avg(increase(logiq_data_received_bytes[5m])*12/1000000000)/1,0.01)*100"
    }
   ]
  },
  {
   "title": "Daily GB/h",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round(sum(increase(logiq_data_received_bytes[1h]))/1000000000,0.01)"
    }
   ]
  },
  {
   "title": "Total ingested bytes (30d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logiq_data_received_bytes[30d]))/1000000000000,0.01)"
    }
   ]
  },
  {
   "title": "Log events(24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(logiq_message_count[24h]))/1000000,1)"
    }
   ]
  },
  {
   "title": "TB per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "round(sum(increase(logiq_data_received_bytes[24h]))/1000000000000,0.01)"
    }
   ]
  },
  {
   "title": "#Messages/sec by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "round(sum by (exported_namespace) (rate(logiq_namespace_message_count[5m])),1)"
    }
   ]
  },
  {
   "title": "HTTP Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (operation) (rate(logiq_client_connect_count{pod=~\"logiq-flash-\\\\d|logiq-flash-\\\\d\\\\d\",connectionType=\"HTTP\"}[5m]))",
     "legendFormat": "{{connectionType}}"
    }
   ]
  }
 ]
}